@startuml "Domínio - Módulo de Amostras"

abstract class IntIdEntity

class Matriz {
    - identificacao: String
    - assinatura: String
}

class Amostra {
    - identificacao: String
    - assinatura: String
    - matrizes: Matriz[]
}

Amostra --|> IntIdEntity
Amostra "1" o-- "*" Matriz
Matriz --|> IntIdEntity

@enduml