@startuml "Domínio - Módulo Compartilhado"

abstract class "Entity<T>" as EntityT <<abstract>> {
    - id: T
    - ativo: Boolean
    - criadoEm: Date
    - atualizadoEm: Date
}

abstract class IntIdEntity

class Email {
    - endereco: String
}

class TipoTelefone {
    - categoria: String
}

abstract class Telefone {
    - numero: String
    - tipo: TipoTelefone
}

abstract class Endereco {
    - pais: String
    - estado: String
    - cidade: String
    - codigoPostal: String
    - logradouro: String
    - numero: String
    - complemento: String
    - bairro: String
}

abstract class MetodoPagamento {
    - id: Long
    - apelido: String
    - dataCadastro: Date
}

enum TipoChavePix {
    CPF
    CNPJ
    EMAIL
    TELEFONE
    ALEATORIA
}

enum Bandeira {
    VISA
    MASTERCARD
    ELO
    AMEX
    HIPERCARD
}

abstract class CartaoCredito {
    - numeroMascarado: String
    - bandeira: Bandeira
    - validade: String
    - token: String
}

abstract class ChavePix {
    - chave: String
    - tipoChave: TipoChavePix
}

class UnidadeMedida {
    - id: Long
    - nome: String
    - sigla: String
    - fatorConversao: Double
    - ativa: Boolean
}

Endereco --|> IntIdEntity

IntIdEntity --|> EntityT : Entity<Long>
Telefone --|> IntIdEntity
TipoTelefone --|> IntIdEntity

Telefone o-- TipoTelefone

MetodoPagamento --|> IntIdEntity

ChavePix --|> MetodoPagamento

CartaoCredito --|> MetodoPagamento

CartaoCredito -- Bandeira
ChavePix -- TipoChavePix

UnidadeMedida --|> IntIdEntity


@enduml
