@startuml "Domínio - Módulo Compartilhado"

abstract class "Entity<T>" as EntityT <<abstract>> {
    - id: T
    - ativo: Boolean
    - criadoEm: Date
    - atualizadoEm: Date
}

abstract class IntIdEntity

class Email {
    - endereco: String
}

class TipoTelefone {
    - categoria: String
}

abstract class Telefone {
    - numero: String
    - tipo: TipoTelefone
}

abstract class Endereco {
    - pais: String
    - estado: String
    - cidade: String
    - codigoPostal: String
    - logradouro: String
    - numero: String
    - complemento: String
    - bairro: String
}

Endereco --|> IntIdEntity

IntIdEntity --|> EntityT : Entity<Long>
Telefone --|> IntIdEntity
TipoTelefone --|> IntIdEntity

Telefone o-- TipoTelefone


@enduml
