@startuml "Domínio - Módulo de Usuários"

abstract IntIdEntity
class Email
class Perfil

class Usuario {
    - email: Email
    - senha: String
    - perfil: Perfil
}

Usuario --|> IntIdEntity

Usuario "1" o-- "1" Email
Usuario "1" o-- "1" Perfil

@enduml