@startuml "Domínio - Módulo de Etapas"

abstract class IntIdEntity

class Atividade

class Etapa {
    - descricao: String
    - ordem: Long
    - atividade: Atividade
}

class RelatorioEtapa {
    - etapa: Etapa
}

Etapa --|> IntIdEntity
Etapa "*" o-- "1" Atividade

RelatorioEtapa --|> IntIdEntity
RelatorioEtapa "1" o-- "1" Etapa

@enduml