@startuml "Domínio - Módulo de Clientes"

abstract class IntIdEntity
class Email
abstract class Telefone
abstract class Endereco
abstract class CartaoCredito
abstract class ChavePix

class Cliente {
    - nome: String
    - email: Email
}

class TelefoneCliente {
    - cliente: Cliente
}

class EnderecoCliente {
    - cliente: Cliente
}

class CartaoCreditoCliente {
    - cliente: Cliente
}

class ChavePixCliente {
    - cliente: Cliente
}

Cliente --|> IntIdEntity

TelefoneCliente --|> Telefone
EnderecoCliente --|> Endereco

Cliente "1" o-- "1" Email
TelefoneCliente "*" o-- "1" Cliente
EnderecoCliente "*" o-- "1" Cliente

ChavePixCliente --|> ChavePix
CartaoCreditoCliente --|> CartaoCredito

ChavePixCliente "*" o-- "1" Cliente
CartaoCreditoCliente "*" o-- "1" Cliente

@enduml
